import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import { useRef } from "react";

export default function Home() {
  const googleSignInButton = useRef(null);

  const postLoginToken = async (idToken: any) => {
    const API_URL = "";
    const path = "/v1/oauth/login";

    try {
      const res = await fetch(`${API_URL}${path}`, {
        method: "POST",
        credentials: "include",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify(idToken),
      });
      if (!res.ok) throw new Error("error occurred");
      console.log(res.json());
      return true;
    } catch (err: any) {
      console.error("Error message:", err.message);
      return false;
    }
  };

  const onSignIn = async (res: any) => {
    const { credentials } = res;
    const result = await postLoginToken(credentials);
    console.log(result);
  };

  const onLoadGSI = () => {
    window.google.accounts.id.initialize({
      client_id:
        "260952113847-40bmsga5bub0kgp7lnloij2k0qirhacg.apps.googleusercontent.com",
      callback: onSignIn,
    });

    window.google.accounts.id.renderButton(googleSignInButton.current, {
      theme: "filled_blue",
      size: "large",
      text: "SignIn",
      width: "250",
    });
  };

  return (
    <>
      <Script src="https://accounts.google.com/gsi/client" onLoad={onLoadGSI} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button ref={googleSignInButton}></button>
      </main>
    </>
  );
}
